export const ERROR_CODE = {
  SUCCESS: 'Successfully',
  FAILED: 'Failed, try again',
  VALIDATION_ERROR: 'Validation error',
  ERROR_SYSTEM: 'Error system',
  UNAUTHORIZED: 'Unauthorized',
  FORBIDDEN: 'Forbidden',
  BAD_REQUEST: 'Bad Request',
  NOT_FOUND: 'Not found',
  ACCESS_DENIED: 'Access Denied',
  NO_DATA_SUBMITTED: 'No data submitted',
  USER_NOT_FOUND: 'User not found',
  PASSWORD_INCORRECT: 'Password incorrect',
  OLD_PASSWORD_INCORRECT: 'Old password is incorrect',
  EMAIL_EXIST: 'Email already existed',
  CREATE_FAILED: 'Create failed',
  UPDATE_FAILED: 'Update failed',
  DELETE_FAILED: 'Delete failed',
  USER_NOT_DELETE: 'User can not delete',
  CAN_NOT_DELETE_YOURSELF: 'Can not delete yourself',
  USER_NOT_UPDATE: 'User can not update',
  ROLE_EXIST: 'Role already exist',
  ROLE_NOT_FOUND: 'Role not found',
  USER_NOT_ACTIVE: 'User not active',
  LOGIN_FAILED: 'Login failed',
  API_NOT_AVAILABLE: 'API not available',
  USERNAME_INCORRECT: 'Username or password is incorrect',
  TOKEN_EXPIRED: 'Token expired',
  LOGOUT_FAILED: 'Logout failed',
  CHANGE_PASSWORD_FAILED: 'Change password failed',
  FILE_IS_REQUIRED: 'File is required',
  VALIDATION_FAILED: 'Validation failed',
};
